name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger:
  branches:
    include:
      - master
      - refs/tags/*
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: .cicd/checks.sh
  displayName: 'Checks'
- script: .cicd/test.sh
  displayName: 'Test'
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Coverage Results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/coverage.xml'
    #failIfCoverageEmpty: true # Optional
- script: git reset --hard HEAD; git clean -fdx
  displayName: Clean
- script: .cicd/build.sh
  displayName: 'Build'
- script: .cicd/docker.sh
  displayName: 'Docker Build'
- script: .cicd/push.sh
  env:
    jettechPassword: $(jettechPassword)
  displayName: 'Docker Push'
  condition: startsWith(variables['isTag'], 'true')